version: '3'

services:
  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_symfony
    volumes:
      - symfony-db:/var/lib/mysql
  symfony:
    # image: docker.io/bitnami/symfony:5.4.2
    build: .
    ports:
      - '8000:8000'
    environment:
      - SYMFONY_DATABASE_HOST=mysql
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=root
      - SYMFONY_DATABASE_NAME=test_symfony
      - SYMFONY_DATABASE_PASSWORD=password
    volumes:
      - './:/app'
    depends_on:
      - mysql
volumes:
  symfony-db:
